data:
  mnist:
    train_images: "data/raw/train-images.idx3-ubyte"
    train_labels: "data/raw/train-labels.idx1-ubyte"
    test_images:  "data/raw/t10k-images.idx3-ubyte"
    test_labels:  "data/raw/t10k-labels.idx1-ubyte"
  processed_root: "data/processed/mnist_tl"

preprocess:
  resize: [224, 224]          # for transfer learning backbones
  duplicate_channels: 3       # 1->3 channels (RGB)
  imagenet_norm: true         # normalize with ImageNet stats

# ImageNet stats (kept for reference; normalization is done at train time usually)
imagenet:
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]