
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1zpQBTX9wHW6gFlcWIL_ntKHmBB6jd8xP/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data


data_preprocessing:
  titanic:
    train_csv: artifacts/data_ingestion/unzipped_data/train.csv
    test_csv: artifacts/data_ingestion/unzipped_data/test.csv
    processed_root: artifacts/data_preprocessing/processed_titanic

model_training:
  train_data_path: artifacts/data_preprocessing/processed_titanic/train.parquet
  test_data_path: artifacts/data_preprocessing/processed_titanic/test.parquet
  label_col: Survived
  features_col: features
  reg_params: [0.01, 0.1, 1.0]
  elastic_net_params: [0.0, 0.5, 1.0]
  num_folds: 3