artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1mOER_E4PyqR-EcSZ8eXGyV5EaQ1nSMJU/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5





data_preprocessing:
  mnist:
    train_images: artifacts/data_ingestion/unzipped_data/train-images.idx3-ubyte
    train_labels: artifacts/data_ingestion/unzipped_data/train-labels.idx1-ubyte
    test_images: artifacts/data_ingestion/unzipped_data/t10k-images.idx3-ubyte
    test_labels: artifacts/data_ingestion/unzipped_data/t10k-labels.idx1-ubyte
  processed_root: artifacts/data_preprocessing/processed_mnist
  resize: [224, 224]